# Generated by Django 4.1.4 on 2023-04-21 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_author_e_main_address_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caption',
            new_name='tags',
        ),
    ]
