# Generated by Django 4.1.4 on 2023-04-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_caption_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email_address',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='post',
            name='image_name',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
